language: cpp
compiler:
    - clang
    - gcc
    
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-7.0
          packages:
            - clang-7.0
      env:
        - MATRIX_EVAL="CC=clang-7.0 && CXX=clang++-7.0"

before_install:
    - eval "${MATRIX_EVAL}"
    
install:
    - sudo apt-get install -y libsfml-dev

before_script:
    - chmod +x build_library.sh

script: 
    - ./build_library.sh