language: cpp
    
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-7 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-7
            - libllvm7
            - libstdc++6
            - libstdc++-4.9-dev
            - libgcc-4.9-dev
            - libobjc-4.9-dev
            - libclang-common-7-dev
            - libclang1-7
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"

before_install:
    - eval "${MATRIX_EVAL}"
    
install:
    - sudo apt-get install -y libsfml-dev

before_script:
    - chmod +x build_library.sh

script: 
    - ./build_library.sh